-- Bulk seed of the full 137-item menu (Chips, Cup Noodles, Biscuits, Cakes,
-- Ice Cream, Chocolates, Drinks, Hot, Cold, Maggie, Sandwich, Omelette,
-- Burger), matching the exact category/brand structure the app already
-- renders (CATEGORY_BRANDS in src/App.tsx). Applied directly to the live
-- database. Safe to re-run (on conflict do nothing).
--
-- NOTE: Cold Coffee and Lemon Tea prices were illegible in the source photo
-- this catalog was transcribed from; placeholder prices (Rs 35 / Rs 15) were
-- used and should be corrected via Owner Dashboard once confirmed.

insert into public.coke_station_menu (id, name, category, size, price, emoji, available, brand)
values
('chips-max-protein-peri-peri-regular', 'Peri Peri', 'Chips', 'Regular', 45, '🍽️', true, 'Max Protein'),
('chips-max-protein-cream-onion-regular', 'Cream & Onion', 'Chips', 'Regular', 45, '🍽️', true, 'Max Protein'),
('chips-max-protein-barbecue-regular', 'Barbecue', 'Chips', 'Regular', 45, '🍽️', true, 'Max Protein'),
('chips-max-protein-gochujang-regular', 'Gochujang', 'Chips', 'Regular', 45, '🍽️', true, 'Max Protein'),
('chips-bingo-original-style-regular', 'Original Style', 'Chips', 'Regular', 50, '🍽️', true, 'Bingo'),
('chips-bingo-korean-style-regular', 'Korean Style', 'Chips', 'Regular', 50, '🍽️', true, 'Bingo'),
('chips-bingo-mad-angles-achari-masti-regular', 'Mad Angles Achari Masti', 'Chips', 'Regular', 50, '🍽️', true, 'Bingo'),
('chips-bingo-very-peri-peri-regular', 'Very Peri Peri', 'Chips', 'Regular', 50, '🍽️', true, 'Bingo'),
('chips-lays-cream-onion-regular', 'Cream & Onion', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-magic-masala-regular', 'Magic Masala', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-tangy-tomato-regular', 'Tangy Tomato', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-kurkure-masala-munch-regular', 'Kurkure Masala Munch', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-bingo-tangy-tomato-regular', 'Bingo Tangy Tomato', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-bingo-cream-onion-regular', 'Bingo Cream & Onion', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('chips-lays-bingo-achari-masti-regular', 'Bingo Achari Masti', 'Chips', 'Regular', 20, '🍽️', true, 'Lays'),
('cup-noodles-chicken-chumky-spicy-cup', 'Chicken Chumky Spicy', 'Cup Noodles', 'Cup', 60, '🍽️', true, null),
('cup-noodles-italian-delight-cup', 'Italian Delight', 'Cup Noodles', 'Cup', 60, '🍽️', true, null),
('cup-noodles-veg-manchow-cup', 'Veg Manchow', 'Cup Noodles', 'Cup', 60, '🍽️', true, null),
('cup-noodles-delicious-masala-cup', 'Delicious Masala', 'Cup Noodles', 'Cup', 60, '🍽️', true, null),
('cup-noodles-hot-chilli-cup', 'Hot Chilli', 'Cup Noodles', 'Cup', 60, '🍽️', true, null),
('cup-noodles-maggi-spicy-cheesy-cup-cup', 'Maggi Spicy Cheesy Cup', 'Cup Noodles', 'Cup', 65, '🍽️', true, null),
('biscuits-hide-seek-pack', 'Hide & Seek', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-monaco-cheese-pack', 'Monaco Cheese', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-monaco-classic-pack', 'Monaco Classic', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-monaco-choco-nut-pack', 'Monaco Choco Nut', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-mcvitie-s-hobnobs-pack', 'McVitie''s Hobnobs', 'Biscuits', 'Pack', 35, '🍽️', true, null),
('biscuits-dark-fantasy-bourbon-pack', 'Dark Fantasy Bourbon', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-jim-jam-pack', 'Jim Jam', 'Biscuits', 'Pack', 40, '🍽️', true, null),
('biscuits-dark-fantasy-vanilla-sandwich-pack', 'Dark Fantasy Vanilla Sandwich', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-dark-fantasy-chocolate-sandwich-pack', 'Dark Fantasy Chocolate Sandwich', 'Biscuits', 'Pack', 30, '🍽️', true, null),
('biscuits-bourbon-pack', 'Bourbon', 'Biscuits', 'Pack', 40, '🍽️', true, null),
('cakes-treat-croissant-piece', 'Treat Croissant', 'Cakes', 'Piece', 50, '🍽️', true, null),
('cakes-goobles-fruit-fun-piece', 'Goobles Fruit Fun', 'Cakes', 'Piece', 30, '🍽️', true, null),
('cakes-goobles-choco-chills-piece', 'Goobles Choco Chills', 'Cakes', 'Piece', 30, '🍽️', true, null),
('cakes-plain-cake-piece', 'Plain Cake', 'Cakes', 'Piece', 16, '🍽️', true, null),
('cakes-pudding-cake-piece', 'Pudding Cake', 'Cakes', 'Piece', 16, '🍽️', true, null),
('cakes-jam-roll-piece', 'Jam Roll', 'Cakes', 'Piece', 16, '🍽️', true, null),
('cakes-chocolate-roll-piece', 'Chocolate Roll', 'Cakes', 'Piece', 16, '🍽️', true, null),
('cakes-honey-cake-piece', 'Honey Cake', 'Cakes', 'Piece', 16, '🍽️', true, null),
('cakes-cream-bun-piece', 'Cream Bun', 'Cakes', 'Piece', 18, '🍽️', true, null),
('cakes-brownie-cupcakes-piece', 'Brownie Cupcakes', 'Cakes', 'Piece', 20, '🍽️', true, null),
('cakes-brownie-cake-piece', 'Brownie Cake', 'Cakes', 'Piece', 50, '🍽️', true, null),
('ice-cream-dairy-day-choco-bar-regular', 'Choco Bar', 'Ice Cream', 'Regular', 20, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-milky-yumm-regular', 'Milky Yumm', 'Ice Cream', 'Regular', 20, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-alphonso-mango-regular', 'Alphonso Mango', 'Ice Cream', 'Regular', 20, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-vanilla-paddle-regular', 'Vanilla Paddle', 'Ice Cream', 'Regular', 25, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-rose-pearl-ice-regular', 'Rose Pearl Ice', 'Ice Cream', 'Regular', 25, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-rabadi-kulfi-regular', 'Rabadi Kulfi', 'Ice Cream', 'Regular', 25, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-malai-kulfi-regular', 'Malai Kulfi', 'Ice Cream', 'Regular', 30, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-triple-bar-chocolate-regular', 'Triple Bar Chocolate', 'Ice Cream', 'Regular', 40, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-triple-bar-coffee-regular', 'Triple Bar Coffee', 'Ice Cream', 'Regular', 40, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-triple-bar-butterscotch-regular', 'Triple Bar Butterscotch', 'Ice Cream', 'Regular', 40, '🍽️', true, 'Dairy Day'),
('ice-cream-dairy-day-belgian-cone-regular', 'Belgian Cone', 'Ice Cream', 'Regular', 50, '🍽️', true, 'Dairy Day'),
('ice-cream-mercely-s-choco-bar-regular', 'Choco Bar', 'Ice Cream', 'Regular', 35, '🍽️', true, 'Mercely''s'),
('ice-cream-mercely-s-chocolate-cone-regular', 'Chocolate Cone', 'Ice Cream', 'Regular', 50, '🍽️', true, 'Mercely''s'),
('ice-cream-mercely-s-butterscotch-regular', 'Butterscotch', 'Ice Cream', 'Regular', 50, '🍽️', true, 'Mercely''s'),
('ice-cream-mercely-s-blue-berry-cone-regular', 'Blue Berry Cone', 'Ice Cream', 'Regular', 60, '🍽️', true, 'Mercely''s'),
('ice-cream-mercely-s-red-velvet-cone-regular', 'Red Velvet Cone', 'Ice Cream', 'Regular', 60, '🍽️', true, 'Mercely''s'),
('ice-cream-mercely-s-tender-coconut-bar-regular', 'Tender Coconut Bar', 'Ice Cream', 'Regular', 60, '🍽️', true, 'Mercely''s'),
('chocolates-nestl-milky-bar-regular', 'Milky Bar', 'Chocolates', 'Regular', 20, '🍽️', true, 'Nestlé'),
('chocolates-nestl-moosha-milky-bar-regular', 'Moosha Milky Bar', 'Chocolates', 'Regular', 20, '🍽️', true, 'Nestlé'),
('chocolates-nestl-kitkat-small', 'KitKat', 'Chocolates', 'Small', 20, '🍽️', true, 'Nestlé'),
('chocolates-nestl-kitkat-large', 'KitKat', 'Chocolates', 'Large', 30, '🍽️', true, 'Nestlé'),
('chocolates-nestl-munch-max-brownie-regular', 'Munch Max Brownie', 'Chocolates', 'Regular', 25, '🍽️', true, 'Nestlé'),
('chocolates-nestl-munch-max-nuts-regular', 'Munch Max Nuts', 'Chocolates', 'Regular', 25, '🍽️', true, 'Nestlé'),
('chocolates-nestl-munch-regular', 'Munch', 'Chocolates', 'Regular', 20, '🍽️', true, 'Nestlé'),
('chocolates-nestl-choco-delite-regular', 'Choco Delite', 'Chocolates', 'Regular', 10, '🍽️', true, 'Nestlé'),
('chocolates-rite-bite-chocolates-sports-bar-regular', 'Sports Bar', 'Chocolates', 'Regular', 45, '🍽️', true, 'Rite Bite Chocolates'),
('chocolates-rite-bite-chocolates-yogurt-berry-regular', 'Yogurt Berry', 'Chocolates', 'Regular', 45, '🍽️', true, 'Rite Bite Chocolates'),
('chocolates-rite-bite-chocolates-choco-delite-regular', 'Choco Delite', 'Chocolates', 'Regular', 45, '🍽️', true, 'Rite Bite Chocolates'),
('chocolates-rite-bite-chocolates-peanut-butter-regular', 'Peanut Butter', 'Chocolates', 'Regular', 45, '🍽️', true, 'Rite Bite Chocolates'),
('drinks-cavin-s-chocolate-milk-shake-regular', 'Chocolate Milk Shake', 'Drinks', 'Regular', 40, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-vanilla-milk-shake-regular', 'Vanilla Milk Shake', 'Drinks', 'Regular', 40, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-butterscotch-regular', 'Butterscotch', 'Drinks', 'Regular', 40, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-belgian-milk-shake-regular', 'Belgian Milk Shake', 'Drinks', 'Regular', 40, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-strawberry-milk-shake-regular', 'Strawberry Milk Shake', 'Drinks', 'Regular', 40, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-rose-lassi-regular', 'Rose Lassi', 'Drinks', 'Regular', 25, '🍽️', true, 'Cavin''s'),
('drinks-cavin-s-masala-chaas-butter-milk-regular', 'Masala Chaas / Butter Milk', 'Drinks', 'Regular', 20, '🍽️', true, 'Cavin''s'),
('drinks-minute-maid-minute-maid-apple-regular', 'Minute Maid Apple', 'Drinks', 'Regular', 10, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-minute-maid-mixed-fruits-regular', 'Minute Maid Mixed Fruits', 'Drinks', 'Regular', 10, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-minute-maid-lemon-regular', 'Minute Maid Lemon', 'Drinks', 'Regular', 20, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-minute-maid-pulpy-orange-regular', 'Minute Maid Pulpy Orange', 'Drinks', 'Regular', 25, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-maaza-small', 'Maaza', 'Drinks', 'Small', 10, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-maaza-large', 'Maaza', 'Drinks', 'Large', 20, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-badam-milk-regular', 'Badam Milk', 'Drinks', 'Regular', 35, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-appy-fizz-regular', 'Appy Fizz', 'Drinks', 'Regular', 20, '🍽️', true, 'Minute Maid'),
('drinks-minute-maid-real-mango-regular', 'Real Mango', 'Drinks', 'Regular', 20, '🍽️', true, 'Minute Maid'),
('drinks-soft-drinks-limca-740-ml', 'Limca', 'Drinks', '740 ml', 40, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-sprite-740-ml', 'Sprite', 'Drinks', '740 ml', 40, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-coca-cola-740-ml', 'Coca-Cola', 'Drinks', '740 ml', 40, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-fanta-740-ml', 'Fanta', 'Drinks', '740 ml', 40, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-thums-up-740-ml', 'Thums Up', 'Drinks', '740 ml', 40, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-maaza-740-ml', 'Maaza', 'Drinks', '740 ml', 35, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-sprite-250-ml', 'Sprite', 'Drinks', '250 ml', 20, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-coca-cola-250-ml', 'Coca-Cola', 'Drinks', '250 ml', 20, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-thums-up-250-ml', 'Thums Up', 'Drinks', '250 ml', 20, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-fanta-250-ml', 'Fanta', 'Drinks', '250 ml', 20, '🍽️', true, 'Soft Drinks'),
('drinks-soft-drinks-limca-250-ml', 'Limca', 'Drinks', '250 ml', 20, '🍽️', true, 'Soft Drinks'),
('drinks-o-cean-mango-regular', 'Mango', 'Drinks', 'Regular', 40, '🍽️', true, 'O''cean'),
('drinks-o-cean-peach-regular', 'Peach', 'Drinks', 'Regular', 40, '🍽️', true, 'O''cean'),
('drinks-o-cean-green-apple-regular', 'Green Apple', 'Drinks', 'Regular', 40, '🍽️', true, 'O''cean'),
('drinks-o-cean-red-apple-regular', 'Red Apple', 'Drinks', 'Regular', 40, '🍽️', true, 'O''cean'),
('drinks-o-cean-guava-regular', 'Guava', 'Drinks', 'Regular', 40, '🍽️', true, 'O''cean'),
('drinks-o-cean-water-bottle-regular', 'Water Bottle', 'Drinks', 'Regular', 20, '🍽️', true, 'O''cean'),
('hot-coffee-cup', 'Coffee', 'Hot', 'Cup', 25, '🍽️', true, null),
('hot-boost-cup', 'Boost', 'Hot', 'Cup', 30, '🍽️', true, null),
('hot-horlicks-cup', 'Horlicks', 'Hot', 'Cup', 30, '🍽️', true, null),
('hot-hot-chocolate-cup', 'Hot Chocolate', 'Hot', 'Cup', 40, '🍽️', true, null),
('hot-black-coffee-cup', 'Black Coffee', 'Hot', 'Cup', 16, '🍽️', true, null),
('cold-cold-coffee-glass', 'Cold Coffee', 'Cold', 'Glass', 35, '🍽️', true, null),
('cold-lemon-tea-glass', 'Lemon Tea', 'Cold', 'Glass', 15, '🍽️', true, null),
('maggie-plain-maggi-regular', 'Plain Maggi', 'Maggie', 'Regular', 35, '🍽️', true, null),
('maggie-cheese-maggi-regular', 'Cheese Maggi', 'Maggie', 'Regular', 48, '🍽️', true, null),
('maggie-veg-fried-maggi-regular', 'Veg Fried Maggi', 'Maggie', 'Regular', 40, '🍽️', true, null),
('maggie-egg-fried-maggi-regular', 'Egg Fried Maggi', 'Maggie', 'Regular', 50, '🍽️', true, null),
('maggie-chicken-fried-maggi-regular', 'Chicken Fried Maggi', 'Maggie', 'Regular', 65, '🍽️', true, null),
('maggie-veg-fried-with-cheese-maggi-regular', 'Veg Fried with Cheese Maggi', 'Maggie', 'Regular', 52, '🍽️', true, null),
('maggie-egg-fried-with-cheese-maggi-regular', 'Egg Fried with Cheese Maggi', 'Maggie', 'Regular', 62, '🍽️', true, null),
('maggie-chicken-fried-with-cheese-maggi-regular', 'Chicken Fried with Cheese Maggi', 'Maggie', 'Regular', 77, '🍽️', true, null),
('sandwich-veg-sandwich-regular', 'Veg Sandwich', 'Sandwich', 'Regular', 37, '🍽️', true, null),
('sandwich-veg-cheese-sandwich-regular', 'Veg Cheese Sandwich', 'Sandwich', 'Regular', 49, '🍽️', true, null),
('sandwich-paneer-sandwich-regular', 'Paneer Sandwich', 'Sandwich', 'Regular', 52, '🍽️', true, null),
('sandwich-paneer-cheese-sandwich-regular', 'Paneer Cheese Sandwich', 'Sandwich', 'Regular', 64, '🍽️', true, null),
('sandwich-chicken-sandwich-regular', 'Chicken Sandwich', 'Sandwich', 'Regular', 57, '🍽️', true, null),
('sandwich-chicken-cheese-sandwich-regular', 'Chicken Cheese Sandwich', 'Sandwich', 'Regular', 69, '🍽️', true, null),
('sandwich-chilli-cheese-sandwich-regular', 'Chilli Cheese Sandwich', 'Sandwich', 'Regular', 39, '🍽️', true, null),
('sandwich-plain-cheese-sandwich-regular', 'Plain Cheese Sandwich', 'Sandwich', 'Regular', 29, '🍽️', true, null),
('omelette-omelette-regular', 'Omelette', 'Omelette', 'Regular', 24, '🍽️', true, null),
('omelette-bread-omelette-regular', 'Bread Omelette', 'Omelette', 'Regular', 34, '🍽️', true, null),
('omelette-bread-cheese-omelette-regular', 'Bread Cheese Omelette', 'Omelette', 'Regular', 52, '🍽️', true, null),
('omelette-chicken-bread-omelette-regular', 'Chicken Bread Omelette', 'Omelette', 'Regular', 62, '🍽️', true, null),
('omelette-chicken-cheese-bread-omelette-regular', 'Chicken Cheese Bread Omelette', 'Omelette', 'Regular', 74, '🍽️', true, null),
('omelette-chilli-cheese-omelette-regular', 'Chilli Cheese Omelette', 'Omelette', 'Regular', 36, '🍽️', true, null),
('omelette-chicken-omelette-regular', 'Chicken Omelette', 'Omelette', 'Regular', 37, '🍽️', true, null),
('burger-veg-peri-peri-regular', 'Veg Peri Peri', 'Burger', 'Regular', 62, '🍽️', true, null),
('burger-chicken-peri-peri-regular', 'Chicken Peri Peri', 'Burger', 'Regular', 88, '🍽️', true, null),
('burger-paneer-peri-peri-regular', 'Paneer Peri Peri', 'Burger', 'Regular', 77, '🍽️', true, null)
on conflict (id) do nothing;
